### ISSUE TITLE
JSONP: Uncaught ReferenceError

### ISSUE THREAD

**Issue by arvinsim** [camsong/fetch-jsonp#30]
I am not sure why this library does not work with a url from AirBnB. I have posted a question about it in StackOverflow.

http://stackoverflow.com/questions/42869123/jsonp-uncaught-referenceerror

**Comment by mAAdhaTTah** [comment]
We started experiencing this "issue" recently, but I believe it's just a result of the request timing out and the library deleting the global function, then the request completing afterwards.

**Comment by doxiaodong** [comment]
https://github.com/camsong/fetch-jsonp/pull/29
see here, there is no way to cancel the script request.

**Comment by ryanyun** [comment]
I'm running into this issue here too...

So far, I've been able to confirm that it successfully fetches the JSONP data by defining `window.search_results()`. In your example, it would be:
```
fetchJsonp('http://assets.airbnb.com/frontend/search_results.js')
window.search_results = function(json){
   debugger; // json = Array(20)
   return json
}
```
At the point of the debugger, it does have the JSON. However, I would like it to be the return value outside of the scope of `window.search_results()`

i.e.:
```
fetchJsonp('http://assets.airbnb.com/frontend/search_results.js')
window.search_results = function(json){
   debugger; // json = Array(20)
   return json
}
debugger; // i want access to json here
```

**Comment by camsong** [comment]
You should use `jsonpCallbackFunction` instead of `jsonpCallback`.

```js
fetchJsonp('http://assets.airbnb.com/frontend/search_results.js', {
  jsonpCallbackFunction: 'search_results',
})
```
